# Generated by Django 4.2.7 on 2024-01-20 10:46

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Запрос клиента',
                'verbose_name_plural': 'Запросы клиентов',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_unread', models.PositiveIntegerField(default=0, verbose_name='Количество непрочитанных сообщений')),
                ('last_message_created', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата создания последнего сообщения')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['-count_unread'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное имя')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Номер')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Покупателя',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('type', models.CharField(verbose_name='Тип обьекта')),
                ('details', models.TextField(verbose_name='Описание обьекта')),
                ('location', models.CharField(max_length=100, verbose_name='Местоположение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('currency', models.CharField(max_length=9, verbose_name='Валюта')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Сдан?')),
            ],
            options={
                'verbose_name': 'Недвижимость',
                'verbose_name_plural': 'Недвижимость',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID пользователя в Telegram')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='Ссылка на пользователя')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Телеграм менеджер',
                'verbose_name_plural': 'Телеграм менеджер',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'verbose_name': 'Администратора',
                'verbose_name_plural': 'Администраторы сайта',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threade', models.CharField(max_length=150, verbose_name='Идентификатор треда')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.tguser', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('text', models.TextField(help_text='Укажите текст', max_length=3000, verbose_name='Текст')),
                ('mail_date', models.DateTimeField(help_text='Укажите дату рассылки', verbose_name='Дата рассылки')),
                ('is_sended', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('buyer_inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.buyerinquiry', verbose_name='Запрос клиента')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('message_id', models.PositiveIntegerField(default=None, null=True, unique=True, verbose_name='ID сообщения')),
                ('text', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочтено')),
                ('sender', models.CharField(choices=[('user', 'Пользователь'), ('bot', 'Бот')], max_length=20)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bot.chat', verbose_name='Переписка с пользователем')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('key', 'value')},
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='bot.tguser', verbose_name='Чат с пользователем'),
        ),
        migrations.AddField(
            model_name='buyerinquiry',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='bot.client'),
        ),
        migrations.AddField(
            model_name='buyerinquiry',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.property', verbose_name='Недвижимость'),
        ),
        migrations.AddField(
            model_name='buyerinquiry',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_inquiry', to='bot.tguser', verbose_name='Агент'),
        ),
    ]
