# Generated by Django 4.2.7 on 2023-11-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='currency',
            field=models.CharField(max_length=9, verbose_name='Валюта'),
        ),
    ]
