# Generated by Django 4.2.7 on 2024-01-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='build_year',
            field=models.CharField(max_length=50, null=True, verbose_name='Год постройки'),
        ),
    ]
