# Generated by Django 4.2.7 on 2024-01-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_property_build_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.CharField(max_length=100, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='property',
            name='street',
            field=models.CharField(max_length=100, null=True, verbose_name='Улица'),
        ),
    ]
