# Generated by Django 4.2.7 on 2024-01-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_property_district_alter_property_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='building_number',
            field=models.CharField(max_length=10, null=True, verbose_name='Номер здания'),
        ),
    ]
