# Generated by Django 4.2.7 on 2024-01-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_property_building_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
